"""Seed 450+ products with ultra-diverse brands for TrustLens."""
import asyncio
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from backend.config import settings
from backend.db.models import Base
from backend.db import repositories as repos

SEED_PRODUCTS_ULTRA = [
    # TWS Earbuds - 50 products (diverse brands)
    ("boAt Airdopes 141", "boat-airdopes-141", "tws-earbuds", "boAt"),
    ("Noise Buds Pro", "noise-buds-pro", "tws-earbuds", "Noise"),
    ("Realme Buds Air 3S", "realme-buds-air-3s", "tws-earbuds", "Realme"),
    ("OnePlus Buds Z2", "oneplus-buds-z2", "tws-earbuds", "OnePlus"),
    ("Mivi DuoPods M70", "mivi-duopods-m70", "tws-earbuds", "Mivi"),
    ("Fire-Boltt Beast", "fire-boltt-beast", "tws-earbuds", "Fire-Boltt"),
    ("Ambrane Dot", "ambrane-dot", "tws-earbuds", "Ambrane"),
    ("Sony WF-C700N", "sony-wf-c700n", "tws-earbuds", "Sony"),
    ("Samsung Galaxy Buds2 Pro", "samsung-galaxy-buds2-pro", "tws-earbuds", "Samsung"),
    ("Apple AirPods Pro", "apple-airpods-pro", "tws-earbuds", "Apple"),
    ("JBL Live Flex", "jbl-live-flex", "tws-earbuds", "JBL"),
    ("Soundcore Space A40", "soundcore-space-a40", "tws-earbuds", "Soundcore"),
    ("Anker Soundcore Liberty 4", "anker-soundcore-liberty-4", "tws-earbuds", "Anker"),
    ("Sennheiser Momentum True Wireless 4", "sennheiser-mtw4", "tws-earbuds", "Sennheiser"),
    ("Nothing Ear 2", "nothing-ear-2", "tws-earbuds", "Nothing"),
    ("Boat Airdopes 131", "boat-airdopes-131", "tws-earbuds", "boAt"),
    ("Noise Icon Pro", "noise-icon-pro", "tws-earbuds", "Noise"),
    ("Realme Buds T300", "realme-buds-t300", "tws-earbuds", "Realme"),
    ("Xiaomi Buds 4", "xiaomi-buds-4", "tws-earbuds", "Xiaomi"),
    ("Oppo Enco Air 3", "oppo-enco-air-3", "tws-earbuds", "Oppo"),
    ("Vivo TWS 3", "vivo-tws-3", "tws-earbuds", "Vivo"),
    ("Poco Pods 2", "poco-pods-2", "tws-earbuds", "Poco"),
    ("Motorola Edge Buds", "motorola-edge-buds", "tws-earbuds", "Motorola"),
    ("Technics EAH-AZ80", "technics-eah-az80", "tws-earbuds", "Technics"),
    ("Philips TAT8606", "philips-tat8606", "tws-earbuds", "Philips"),
    ("Bowers & Wilkins Pi8", "bowers-wilkins-pi8", "tws-earbuds", "Bowers & Wilkins"),
    ("Bang & Olufsen Beoplay EQ", "bang-olufsen-beoplay-eq", "tws-earbuds", "Bang & Olufsen"),
    ("Beats Studio Pro", "beats-studio-pro", "tws-earbuds", "Beats"),
    ("Corsair True Wireless", "corsair-true-wireless", "tws-earbuds", "Corsair"),
    ("HyperX Cloud Buds Pro", "hyperx-cloud-buds-pro", "tws-earbuds", "HyperX"),
    ("SteelSeries Arctis Prime", "steelseries-arctis-prime", "tws-earbuds", "SteelSeries"),
    ("Razer Hammerhead True Wireless X", "razer-hammerhead-twx", "tws-earbuds", "Razer"),
    ("Edifier HECATE GM4 Pro", "edifier-hecate-gm4", "tws-earbuds", "Edifier"),
    ("Soundmagic E11BT Pro", "soundmagic-e11bt-pro", "tws-earbuds", "Soundmagic"),
    ("Audio-Technica ATH-SQ1TW", "audio-technica-ath-sq1tw", "tws-earbuds", "Audio-Technica"),
    ("Huawei FreeBuds 5", "huawei-freebuds-5", "tws-earbuds", "Huawei"),
    ("Honor Earbuds 3 Pro", "honor-earbuds-3-pro", "tws-earbuds", "HONOR"),
    ("Iqoo TWS 1", "iqoo-tws-1", "tws-earbuds", "iQOO"),
    ("Carl F Bucherer Smartwatch", "cf-bucherer-smart", "tws-earbuds", "Carl F Bucherer"),
    ("Bose QuietComfort Ultra", "bose-qc-ultra", "tws-earbuds", "Bose"),
    ("Shure AONIC 50", "shure-aonic-50", "tws-earbuds", "Shure"),
    ("Ultimate Ears Boom Pro", "ue-boom-pro", "tws-earbuds", "Ultimate Ears"),
    ("Marshall Major IV", "marshall-major-iv", "tws-earbuds", "Marshall"),
    ("Turtle Beach Stealth 700", "turtle-beach-stealth", "tws-earbuds", "Turtle Beach"),
    ("Astro A30", "astro-a30", "tws-earbuds", "Astro Gaming"),
    ("SCUF Audio Pro", "scuf-audio-pro", "tws-earbuds", "SCUF"),
    ("Mad Catz Strike 1", "mad-catz-strike-1", "tws-earbuds", "Mad Catz"),

    # Smartwatches - 50 products
    ("Noise ColorFit Pro 4", "noise-colorfit-pro-4", "smartwatches", "Noise"),
    ("boAt Storm", "boat-storm", "smartwatches", "boAt"),
    ("Fire-Boltt Venus", "fire-boltt-venus", "smartwatches", "Fire-Boltt"),
    ("Realme Watch 4", "realme-watch-4", "smartwatches", "Realme"),
    ("Amazfit GTS 4", "amazfit-gts-4", "smartwatches", "Amazfit"),
    ("Mi Watch Revolve", "mi-watch-revolve", "smartwatches", "Xiaomi"),
    ("HONOR Band 7", "honor-band-7", "smartwatches", "HONOR"),
    ("Samsung Galaxy Watch5", "samsung-galaxy-watch5", "smartwatches", "Samsung"),
    ("Apple Watch Series 8", "apple-watch-series-8", "smartwatches", "Apple"),
    ("Garmin Venu 2", "garmin-venu-2", "smartwatches", "Garmin"),
    ("Fitbit Sense 2", "fitbit-sense-2", "smartwatches", "Fitbit"),
    ("Huawei Watch GT 3", "huawei-watch-gt-3", "smartwatches", "Huawei"),
    ("Boat Wave Elite", "boat-wave-elite", "smartwatches", "boAt"),
    ("Noise ColorFit Ultra", "noise-colorfit-ultra", "smartwatches", "Noise"),
    ("Oppo Watch 3", "oppo-watch-3", "smartwatches", "Oppo"),
    ("Vivo Watch 2", "vivo-watch-2", "smartwatches", "Vivo"),
    ("OnePlus Watch 2", "oneplus-watch-2", "smartwatches", "OnePlus"),
    ("Motorola Moto Watch 70", "motorola-moto-watch-70", "smartwatches", "Motorola"),
    ("Nothing Watch 1", "nothing-watch-1", "smartwatches", "Nothing"),
    ("Fossil Gen 6", "fossil-gen-6", "smartwatches", "Fossil"),
    ("Skagen Falster Gen 6", "skagen-falster-6", "smartwatches", "Skagen"),
    ("TAG Heuer Connected", "tag-heuer-connected", "smartwatches", "TAG Heuer"),
    ("Montblanc Summit 3", "montblanc-summit-3", "smartwatches", "Montblanc"),
    ("Emporio Armani Connected", "emporio-armani-connected", "smartwatches", "Emporio Armani"),
    ("Diesel DieselConnect", "diesel-diesel-connect", "smartwatches", "Diesel"),
    ("TomTom Spark 3", "tomtom-spark-3", "smartwatches", "TomTom"),
    ("Polar Vantage M2", "polar-vantage-m2", "smartwatches", "Polar"),
    ("Coros Pace 3", "coros-pace-3", "smartwatches", "Coros"),
    ("Epson ProSense", "epson-prosense", "smartwatches", "Epson"),
    ("Timex IronMan", "timex-ironman", "smartwatches", "Timex"),
    ("Citizen Watch Promaster", "citizen-promaster", "smartwatches", "Citizen"),
    ("Seiko Prospex", "seiko-prospex", "smartwatches", "Seiko"),
    ("Suunto 9 Baro", "suunto-9-baro", "smartwatches", "Suunto"),
    ("Vivoactive 4", "vivoactive-4", "smartwatches", "Garmin"),
    ("Fenix 7", "fenix-7", "smartwatches", "Garmin"),
    ("ASUS VivoWatch 5", "asus-vivowatch-5", "smartwatches", "ASUS"),
    ("Lenovo CarWatch", "lenovo-carwatch", "smartwatches", "Lenovo"),
    ("Mobvoi TicWatch Pro 3", "mobvoi-ticwatch-pro-3", "smartwatches", "Mobvoi"),
    ("Pebble Time Round", "pebble-time-round", "smartwatches", "Pebble"),
    ("Withings ScanWatch", "withings-scanwatch", "smartwatches", "Withings"),
    ("Nokia Steel HR", "nokia-steel-hr", "smartwatches", "Nokia"),
    ("Google Pixel Watch", "google-pixel-watch", "smartwatches", "Google"),
    ("Meta Ray-Ban Smart", "meta-ray-ban-smart", "smartwatches", "Meta"),
    ("Amazon Halo Band", "amazon-halo-band", "smartwatches", "Amazon"),
    ("Microsoft Band 3", "microsoft-band-3", "smartwatches", "Microsoft"),
    ("Intel VAUNT", "intel-vaunt", "smartwatches", "Intel"),
    ("Qualcomm Snapdragon Wear", "qualcomm-wear", "smartwatches", "Qualcomm"),

    # Wireless Headphones - 50 products
    ("boAt Rockerz 400", "boat-rockerz-400", "wireless-headphones", "boAt"),
    ("JBL Tune 710BT", "jbl-tune-710bt", "wireless-headphones", "JBL"),
    ("Sennheiser HD 450SE", "sennheiser-hd-450se", "wireless-headphones", "Sennheiser"),
    ("Sony WH-CH520", "sony-wh-ch520", "wireless-headphones", "Sony"),
    ("Noise Evolve 2", "noise-evolve-2", "wireless-headphones", "Noise"),
    ("Mivi Super Bass", "mivi-super-bass", "wireless-headphones", "Mivi"),
    ("Realme DIZO GH101", "realme-dizo-gh101", "wireless-headphones", "Realme"),
    ("OneOdio A30", "oneodio-a30", "wireless-headphones", "OneOdio"),
    ("Skullcandy Crusher Evo", "skullcandy-crusher-evo", "wireless-headphones", "Skullcandy"),
    ("Bose QuietComfort 45", "bose-quietcomfort-45", "wireless-headphones", "Bose"),
    ("Audio-Technica ATH-S300BT", "audio-technica-ath-s300bt", "wireless-headphones", "Audio-Technica"),
    ("Corsair HS75 XB", "corsair-hs75-xb", "wireless-headphones", "Corsair"),
    ("HyperX Cloud Stinger 2", "hyperx-cloud-stinger-2", "wireless-headphones", "HyperX"),
    ("SteelSeries Arctis 7", "steelseries-arctis-7", "wireless-headphones", "SteelSeries"),
    ("Razer Blackshark V2", "razer-blackshark-v2", "wireless-headphones", "Razer"),
    ("Turtle Beach Stealth 700 Gen 2", "turtle-beach-stealth-700-2", "wireless-headphones", "Turtle Beach"),
    ("Astro A50 Gen 4", "astro-a50-gen-4", "wireless-headphones", "Astro Gaming"),
    ("Mad Catz Strike Pro", "mad-catz-strike-pro", "wireless-headphones", "Mad Catz"),
    ("PDP LVL50", "pdp-lvl50", "wireless-headphones", "PDP"),
    ("SCUF Vanguard", "scuf-vanguard", "wireless-headphones", "SCUF"),
    ("Edifier W830BT", "edifier-w830bt", "wireless-headphones", "Edifier"),
    ("Soundmagic E11", "soundmagic-e11", "wireless-headphones", "Soundmagic"),
    ("Philips SHL3305", "philips-shl3305", "wireless-headphones", "Philips"),
    ("Technics EAH-A800", "technics-eah-a800", "wireless-headphones", "Technics"),
    ("Pioneer HDJ-S7", "pioneer-hdj-s7", "wireless-headphones", "Pioneer"),
    ("Panasonic RP-BTD10", "panasonic-rp-btd10", "wireless-headphones", "Panasonic"),
    ("Denon AH-GC30", "denon-ah-gc30", "wireless-headphones", "Denon"),
    ("Harman Kardon Onyx Studio", "harman-kardon-onyx", "wireless-headphones", "Harman Kardon"),
    ("Bang & Olufsen Beoplay HX", "bang-olufsen-hx", "wireless-headphones", "Bang & Olufsen"),
    ("Beats Studio Pro", "beats-studio-pro-hp", "wireless-headphones", "Beats"),
    ("Bowers & Wilkins PX7S2", "bowers-wilkins-px7s2", "wireless-headphones", "Bowers & Wilkins"),
    ("AKG K361-BT", "akg-k361-bt", "wireless-headphones", "AKG"),
    ("Beyerdynamic Lagoon ANC", "beyerdynamic-lagoon", "wireless-headphones", "Beyerdynamic"),
    ("Shure AONIC 50", "shure-aonic-50-hp", "wireless-headphones", "Shure"),
    ("Sennheiser Momentum 4", "sennheiser-momentum-4", "wireless-headphones", "Sennheiser"),
    ("Sony WH-1000XM5", "sony-wh-1000xm5", "wireless-headphones", "Sony"),
    ("Apple AirPods Max", "apple-airpods-max", "wireless-headphones", "Apple"),
    ("Samsung Galaxy Buds Studio", "samsung-galaxy-buds-studio", "wireless-headphones", "Samsung"),
    ("Oppo Enco M32", "oppo-enco-m32", "wireless-headphones", "Oppo"),
    ("Vivo XFold Earphones", "vivo-xfold-earphones", "wireless-headphones", "Vivo"),
    ("Xiaomi Mi Headphones", "xiaomi-mi-headphones", "wireless-headphones", "Xiaomi"),
    ("OnePlus Nord Buds", "oneplus-nord-buds", "wireless-headphones", "OnePlus"),
    ("Realme OneMi", "realme-onemi", "wireless-headphones", "Realme"),
    ("Poco Buds Pro", "poco-buds-pro", "wireless-headphones", "Poco"),
    ("Motorola Edge Headphones", "motorola-edge-hp", "wireless-headphones", "Motorola"),
    ("Nothing Earbuds", "nothing-earbuds", "wireless-headphones", "Nothing"),
    ("Honor Magic Earbuds", "honor-magic-earbuds", "wireless-headphones", "HONOR"),

    # Bluetooth Speakers - 50 products
    ("JBL Go 3", "jbl-go-3", "bluetooth-speakers", "JBL"),
    ("boAt Stone 800", "boat-stone-800", "bluetooth-speakers", "boAt"),
    ("UE Boom 3", "ue-boom-3", "bluetooth-speakers", "UE"),
    ("Sony SRS-XB23", "sony-srs-xb23", "bluetooth-speakers", "Sony"),
    ("Noise Buzz Buds", "noise-buzz-buds", "bluetooth-speakers", "Noise"),
    ("Mi Portable Bluetooth Speaker", "mi-portable-bluetooth-speaker", "bluetooth-speakers", "Xiaomi"),
    ("Marshall Kilburn II", "marshall-kilburn-ii", "bluetooth-speakers", "Marshall"),
    ("Ultimate Ears MegaBoom 3", "ue-megaboom-3", "bluetooth-speakers", "UE"),
    ("Anker Soundcore 2", "anker-soundcore-2", "bluetooth-speakers", "Anker"),
    ("Bose SoundLink Mini II", "bose-soundlink-mini-ii", "bluetooth-speakers", "Bose"),
    ("JBL Flip 6", "jbl-flip-6", "bluetooth-speakers", "JBL"),
    ("boAt Stone 650", "boat-stone-650", "bluetooth-speakers", "boAt"),
    ("UE Wonderboom 3", "ue-wonderboom-3", "bluetooth-speakers", "UE"),
    ("Sony SRS-XB33", "sony-srs-xb33", "bluetooth-speakers", "Sony"),
    ("Noise Icon Boom", "noise-icon-boom", "bluetooth-speakers", "Noise"),
    ("Mi Portable Bluetooth Speaker Pro", "mi-portable-speaker-pro", "bluetooth-speakers", "Xiaomi"),
    ("Marshall Emberton II", "marshall-emberton-ii", "bluetooth-speakers", "Marshall"),
    ("JBL Party Box 110", "jbl-party-box-110", "bluetooth-speakers", "JBL"),
    ("boAt Aavante 1200", "boat-aavante-1200", "bluetooth-speakers", "boAt"),
    ("Beats Pill", "beats-pill", "bluetooth-speakers", "Beats"),
    ("Harman Kardon Esquire 2", "harman-kardon-esquire-2", "bluetooth-speakers", "Harman Kardon"),
    ("Bang & Olufsen Beoplay S3", "bang-olufsen-beoplay-s3", "bluetooth-speakers", "Bang & Olufsen"),
    ("Edifier MR4", "edifier-mr4", "bluetooth-speakers", "Edifier"),
    ("Philips BT6000", "philips-bt6000", "bluetooth-speakers", "Philips"),
    ("Soundcore Motion Boom", "soundcore-motion-boom", "bluetooth-speakers", "Soundcore"),
    ("JBL Authentics 500", "jbl-authentics-500", "bluetooth-speakers", "JBL"),
    ("boAt Roar", "boat-roar", "bluetooth-speakers", "boAt"),
    ("Sony SRS-XB100", "sony-srs-xb100", "bluetooth-speakers", "Sony"),
    ("Noise Core", "noise-core", "bluetooth-speakers", "Noise"),
    ("Skullcandy Barricade XL", "skullcandy-barricade-xl", "bluetooth-speakers", "Skullcandy"),
    ("Turtle Beach Battle Station", "turtle-beach-battle", "bluetooth-speakers", "Turtle Beach"),
    ("Corsair SP2500", "corsair-sp2500", "bluetooth-speakers", "Corsair"),
    ("HyperX Alloy Elite", "hyperx-alloy-elite", "bluetooth-speakers", "HyperX"),
    ("Razer Leviathan", "razer-leviathan", "bluetooth-speakers", "Razer"),
    ("SteelSeries Arena 7", "steelseries-arena-7", "bluetooth-speakers", "SteelSeries"),
    ("Mad Catz Frequency", "mad-catz-frequency", "bluetooth-speakers", "Mad Catz"),
    ("SCUF Audio Pro", "scuf-audio-pro-sp", "bluetooth-speakers", "SCUF"),
    ("Denon HEOS 1 HS2", "denon-heos-1", "bluetooth-speakers", "Denon"),
    ("Panasonic SC-RS90B", "panasonic-sc-rs90b", "bluetooth-speakers", "Panasonic"),
    ("Technics SC-C50", "technics-sc-c50", "bluetooth-speakers", "Technics"),
    ("Tivoli Audio SongBook", "tivoli-audio-songbook", "bluetooth-speakers", "Tivoli Audio"),
    ("Sonos Move 2", "sonos-move-2", "bluetooth-speakers", "Sonos"),
    ("Amazon Echo Show 15", "amazon-echo-show-15", "bluetooth-speakers", "Amazon"),
    ("Google Nest Audio Max", "google-nest-audio-max", "bluetooth-speakers", "Google"),
    ("Apple HomePod mini", "apple-homepod-mini", "bluetooth-speakers", "Apple"),
    ("Oppo Enco M32 Speaker", "oppo-enco-m32-sp", "bluetooth-speakers", "Oppo"),
    ("Vivo X Flip Speaker", "vivo-x-flip-speaker", "bluetooth-speakers", "Vivo"),
    ("OnePlus Nord Pad Speaker", "oneplus-nord-pad-sp", "bluetooth-speakers", "OnePlus"),

    # Power Banks - 50 products
    ("Mi Power Bank 3i", "mi-power-bank-3i", "power-banks", "Xiaomi"),
    ("boAt Energyshroom PB500", "boat-energyshroom-pb500", "power-banks", "boAt"),
    ("Realme 30000mAh", "realme-30000mah", "power-banks", "Realme"),
    ("Anker PowerCore Essential 20000", "anker-powercore-essential-20000", "power-banks", "Anker"),
    ("Ambrane PowerBank 10000", "ambrane-powerbank-10000", "power-banks", "Ambrane"),
    ("Noise PowerBank 10000", "noise-powerbank-10000", "power-banks", "Noise"),
    ("Mivi Power Bank 5000", "mivi-power-bank-5000", "power-banks", "Mivi"),
    ("OnePlus Power Bank 10000", "oneplus-power-bank-10000", "power-banks", "OnePlus"),
    ("Samsung Power Bank", "samsung-power-bank", "power-banks", "Samsung"),
    ("Romoss Sense 6", "romoss-sense-6", "power-banks", "Romoss"),
    ("Belkin Boost Charge", "belkin-boost-charge", "power-banks", "Belkin"),
    ("JBL Power Bank", "jbl-power-bank", "power-banks", "JBL"),
    ("Sony Power Bank", "sony-power-bank", "power-banks", "Sony"),
    ("Oppo VOOC Power Bank", "oppo-vooc-pb", "power-banks", "Oppo"),
    ("Vivo Power Bank", "vivo-power-bank", "power-banks", "Vivo"),
    ("Motorola Power Bank", "motorola-power-bank", "power-banks", "Motorola"),
    ("Nothing Power Bank", "nothing-power-bank", "power-banks", "Nothing"),
    ("Poco Power Bank", "poco-power-bank", "power-banks", "Poco"),
    ("HONOR Power Bank", "honor-power-bank", "power-banks", "HONOR"),
    ("iQOO Power Bank", "iqoo-power-bank", "power-banks", "iQOO"),
    ("Infinix Power Bank", "infinix-power-bank", "power-banks", "Infinix"),
    ("Tecno Power Bank", "tecno-power-bank", "power-banks", "Tecno"),
    ("Itel Power Bank", "itel-power-bank", "power-banks", "Itel"),
    ("Micromax Power Bank", "micromax-power-bank", "power-banks", "Micromax"),
    ("InFocus Power Bank", "infocus-power-bank", "power-banks", "InFocus"),
    ("Corsair Crystal Series", "corsair-crystal-series", "power-banks", "Corsair"),
    ("ASUS ROG PD Charger", "asus-rog-pd", "power-banks", "ASUS"),
    ("Lenovo ThinkPad Charger", "lenovo-thinkpad-charger", "power-banks", "Lenovo"),
    ("Dell XPS Charger", "dell-xps-charger", "power-banks", "Dell"),
    ("HP OmniBook Charger", "hp-omnibook-charger", "power-banks", "HP"),
    ("Razer Blade Charger", "razer-blade-charger", "power-banks", "Razer"),
    ("MSI Titan Charger", "msi-titan-charger", "power-banks", "MSI"),
    ("Alienware Power Station", "alienware-power-station", "power-banks", "Alienware"),
    ("Acer Power Bank", "acer-power-bank", "power-banks", "Acer"),
    ("Asus Vivobook Power Bank", "asus-vivobook-pb", "power-banks", "ASUS"),
    ("LG Power Bank", "lg-power-bank", "power-banks", "LG"),
    ("Panasonic Power Bank", "panasonic-power-bank", "power-banks", "Panasonic"),
    ("Philips Power Bank", "philips-power-bank", "power-banks", "Philips"),
    ("Sennheiser Power Bank", "sennheiser-power-bank", "power-banks", "Sennheiser"),
    ("Bose Power Bank", "bose-power-bank", "power-banks", "Bose"),
    ("Pioneer Power Bank", "pioneer-power-bank", "power-banks", "Pioneer"),
    ("Denon Power Bank", "denon-power-bank", "power-banks", "Denon"),
    ("Technics Power Bank", "technics-power-bank", "power-banks", "Technics"),
    ("Harman Kardon Power Bank", "harman-kardon-pb", "power-banks", "Harman Kardon"),
    ("Bang & Olufsen Power Bank", "bang-olufsen-pb", "power-banks", "Bang & Olufsen"),
    ("Apple MagSafe Battery", "apple-magsafe-battery", "power-banks", "Apple"),
    ("Google Pixel Charger", "google-pixel-charger", "power-banks", "Google"),

    # Smartphones - 30 products (diverse brands)
    ("Samsung Galaxy S24", "samsung-galaxy-s24", "smartphones", "Samsung"),
    ("iPhone 15 Pro", "iphone-15-pro", "smartphones", "Apple"),
    ("Xiaomi 14 Ultra", "xiaomi-14-ultra", "smartphones", "Xiaomi"),
    ("OnePlus 12", "oneplus-12", "smartphones", "OnePlus"),
    ("Realme 12 Pro", "realme-12-pro", "smartphones", "Realme"),
    ("Vivo X100", "vivo-x100", "smartphones", "Vivo"),
    ("Oppo Find X7", "oppo-find-x7", "smartphones", "Oppo"),
    ("Motorola Edge 50", "motorola-edge-50", "smartphones", "Motorola"),
    ("Nothing Phone 2", "nothing-phone-2", "smartphones", "Nothing"),
    ("Google Pixel 8 Pro", "google-pixel-8-pro", "smartphones", "Google"),
    ("Poco F5 Pro", "poco-f5-pro", "smartphones", "Poco"),
    ("HONOR 90", "honor-90", "smartphones", "HONOR"),
    ("Huawei P60 Pro", "huawei-p60-pro", "smartphones", "Huawei"),
    ("Asus ROG Phone 8", "asus-rog-phone-8", "smartphones", "ASUS"),
    ("Nubia Z60 Ultra", "nubia-z60-ultra", "smartphones", "Nubia"),
    ("ZTE Axon 50 Ultra", "zte-axon-50-ultra", "smartphones", "ZTE"),
    ("Meizu 21", "meizu-21", "smartphones", "Meizu"),
    ("Nothing CMF Phone 1", "nothing-cmf-phone-1", "smartphones", "Nothing"),
    ("iQOO 12", "iqoo-12", "smartphones", "iQOO"),
    ("Infinix Zero Ultra", "infinix-zero-ultra", "smartphones", "Infinix"),
    ("Tecno Phantom X3 Pro", "tecno-phantom-x3", "smartphones", "Tecno"),
    ("Itel P55", "itel-p55", "smartphones", "Itel"),
    ("Micromax In 2b", "micromax-in-2b", "smartphones", "Micromax"),
    ("LeEco Le Pro 3", "leeco-le-pro-3", "smartphones", "LeEco"),
    ("Lenovo Tab P11 Max", "lenovo-tab-p11", "smartphones", "Lenovo"),
    ("LG V60 ThinQ", "lg-v60-thinq", "smartphones", "LG"),
    ("Sony Xperia 1 V", "sony-xperia-1v", "smartphones", "Sony"),
    ("HTC U23 Pro", "htc-u23-pro", "smartphones", "HTC"),
    ("Fairphone 5", "fairphone-5", "smartphones", "Fairphone"),
    ("TCL 50 Pro", "tcl-50-pro", "smartphones", "TCL"),

    # Laptops - 30 products
    ("MacBook Pro 16", "macbook-pro-16", "laptops", "Apple"),
    ("Dell XPS 15", "dell-xps-15", "laptops", "Dell"),
    ("HP Spectre x360", "hp-spectre-x360", "laptops", "HP"),
    ("ASUS ZenBook 14", "asus-zenbook-14", "laptops", "ASUS"),
    ("Lenovo ThinkPad X1", "lenovo-thinkpad-x1", "laptops", "Lenovo"),
    ("MSI GE66 Raider", "msi-ge66-raider", "laptops", "MSI"),
    ("Razer Blade 16", "razer-blade-16", "laptops", "Razer"),
    ("Samsung Galaxy Book3", "samsung-galaxy-book3", "laptops", "Samsung"),
    ("Acer Swift 3", "acer-swift-3", "laptops", "Acer"),
    ("ASUS TUF Gaming A16", "asus-tuf-gaming-a16", "laptops", "ASUS"),
    ("Alienware M18", "alienware-m18", "laptops", "Alienware"),
    ("Corsair Carbide", "corsair-carbide", "laptops", "Corsair"),
    ("Gigabyte AORUS", "gigabyte-aorus", "laptops", "Gigabyte"),
    ("MSI Stealth 16", "msi-stealth-16", "laptops", "MSI"),
    ("ROG Zephyrus G14", "rog-zephyrus-g14", "laptops", "ASUS"),
    ("Blade Stealth 13", "blade-stealth-13", "laptops", "Razer"),
    ("Google Pixelbook Go", "google-pixelbook-go", "laptops", "Google"),
    ("Microsoft Surface Laptop 5", "microsoft-surface-5", "laptops", "Microsoft"),
    ("Huawei MateBook X Pro", "huawei-matebook-x", "laptops", "Huawei"),
    ("OnePlus Pad Pro", "oneplus-pad-pro", "laptops", "OnePlus"),
    ("Xiaomi Mi Notebook Ultra", "xiaomi-mi-notebook", "laptops", "Xiaomi"),
    ("Realme Book", "realme-book", "laptops", "Realme"),
    ("Vivo BookX", "vivo-bookx", "laptops", "Vivo"),
    ("Oppo Book", "oppo-book", "laptops", "Oppo"),
    ("Motorola Book", "motorola-book", "laptops", "Motorola"),
    ("Poco BookX", "poco-bookx", "laptops", "Poco"),
    ("Itel BookX", "itel-bookx", "laptops", "Itel"),
    ("Tecno MegaBook", "tecno-megabook", "laptops", "Tecno"),
    ("Infinix InBook", "infinix-inbook", "laptops", "Infinix"),
    ("Nothing Book", "nothing-book", "laptops", "Nothing"),

    # Tablets - 30 products
    ("Samsung Galaxy Tab S9", "samsung-galaxy-tab-s9", "tablets", "Samsung"),
    ("iPad Pro 12.9", "ipad-pro-129", "tablets", "Apple"),
    ("Xiaomi Pad 6 Pro", "xiaomi-pad-6-pro", "tablets", "Xiaomi"),
    ("Realme Pad 2", "realme-pad-2", "tablets", "Realme"),
    ("OnePlus Pad", "oneplus-pad", "tablets", "OnePlus"),
    ("Lenovo Tab P12", "lenovo-tab-p12", "tablets", "Lenovo"),
    ("HONOR Pad 8", "honor-pad-8", "tablets", "HONOR"),
    ("Oppo Pad 2", "oppo-pad-2", "tablets", "Oppo"),
    ("Vivo Pad 2", "vivo-pad-2", "tablets", "Vivo"),
    ("Amazon Fire HD 10", "amazon-fire-hd-10", "tablets", "Amazon"),
    ("Google Pixel Tablet", "google-pixel-tablet", "tablets", "Google"),
    ("Microsoft Surface Go 3", "microsoft-surface-go-3", "tablets", "Microsoft"),
    ("Huawei MatePad Pro", "huawei-matepad-pro", "tablets", "Huawei"),
    ("Motorola Tab", "motorola-tab", "tablets", "Motorola"),
    ("Nokia Tab", "nokia-tab", "tablets", "Nokia"),
    ("ASUS VivoTab", "asus-vivotab", "tablets", "ASUS"),
    ("LG Tab G5", "lg-tab-g5", "tablets", "LG"),
    ("Panasonic Toughpad", "panasonic-toughpad", "tablets", "Panasonic"),
    ("Sony Xperia Tab", "sony-xperia-tab", "tablets", "Sony"),
    ("Archos Tab", "archos-tab", "tablets", "Archos"),
    ("Blackberry Tab", "blackberry-tab", "tablets", "BlackBerry"),
    ("HP Slate Tablet", "hp-slate-tablet", "tablets", "HP"),
    ("Fujitsu Stylistic", "fujitsu-stylistic", "tablets", "Fujitsu"),
    ("Toshiba Excite", "toshiba-excite", "tablets", "Toshiba"),
    ("Asus Nexus", "asus-nexus", "tablets", "ASUS"),
    ("Motorola Xoom", "motorola-xoom", "tablets", "Motorola"),
    ("Samsung Note Tab", "samsung-note-tab", "tablets", "Samsung"),
    ("Apple iPad Air", "apple-ipad-air", "tablets", "Apple"),
    ("Poco Pad", "poco-pad", "tablets", "Poco"),
    ("Nothing Pad", "nothing-pad", "tablets", "Nothing"),

    # Cameras - 30 products
    ("Canon EOS R8", "canon-eos-r8", "cameras", "Canon"),
    ("Sony A6700", "sony-a6700", "cameras", "Sony"),
    ("Nikon Z6 III", "nikon-z6-iii", "cameras", "Nikon"),
    ("Fujifilm X-T5", "fujifilm-x-t5", "cameras", "Fujifilm"),
    ("Panasonic S5II", "panasonic-s5ii", "cameras", "Panasonic"),
    ("DJI Osmo Action 4", "dji-osmo-action-4", "cameras", "DJI"),
    ("GoPro Hero 12", "gopro-hero-12", "cameras", "GoPro"),
    ("Insta360 X4", "insta360-x4", "cameras", "Insta360"),
    ("Ricoh Theta Z1X", "ricoh-theta-z1x", "cameras", "Ricoh"),
    ("Blackmagic Pocket 6K", "blackmagic-pocket-6k", "cameras", "Blackmagic"),
    ("RED Komodo", "red-komodo", "cameras", "RED"),
    ("Arri Alexa Mini LF", "arri-alexa-mini", "cameras", "ARRI"),
    ("Leica M11", "leica-m11", "cameras", "Leica"),
    ("Phase One XF IQ4", "phase-one-xf-iq4", "cameras", "Phase One"),
    ("Hasselblad H6D", "hasselblad-h6d", "cameras", "Hasselblad"),
    ("Mamiya RB67", "mamiya-rb67", "cameras", "Mamiya"),
    ("Pentax 67", "pentax-67", "cameras", "Pentax"),
    ("Rolleiflex SL66", "rolleiflex-sl66", "cameras", "Rolleiflex"),
    ("Contax RTS III", "contax-rts-iii", "cameras", "Contax"),
    ("Olympus OM System", "olympus-om-system", "cameras", "Olympus"),
    ("Minolta XE7", "minolta-xe7", "cameras", "Minolta"),
    ("Kiev 6C", "kiev-6c", "cameras", "Kiev"),
    ("Kamera Optica", "kamera-optica", "cameras", "Kamera"),
    ("Bronica S2A", "bronica-s2a", "cameras", "Bronica"),
    ("Pentax 645", "pentax-645", "cameras", "Pentax"),
    ("Mamiya Press", "mamiya-press", "cameras", "Mamiya"),
    ("Graflex Crown Graphic", "graflex-crown", "cameras", "Graflex"),
    ("Linhof Technika", "linhof-technika", "cameras", "Linhof"),
    ("Horseman 910", "horseman-910", "cameras", "Horseman"),
    ("Sinar P2", "sinar-p2", "cameras", "Sinar"),

    # Smartbands - 30 products
    ("Mi Band 8 Pro", "mi-band-8-pro", "smartbands", "Xiaomi"),
    ("Noise Icon Fit", "noise-icon-fit", "smartbands", "Noise"),
    ("Realme Band", "realme-band", "smartbands", "Realme"),
    ("boAt Wristfit Pro", "boat-wristfit-pro", "smartbands", "boAt"),
    ("Fire-Boltt Visfit Pro", "fire-boltt-visfit-pro", "smartbands", "Fire-Boltt"),
    ("OnePlus Band", "oneplus-band", "smartbands", "OnePlus"),
    ("Oppo Band", "oppo-band", "smartbands", "Oppo"),
    ("Vivo Band 3", "vivo-band-3", "smartbands", "Vivo"),
    ("HONOR Band 8", "honor-band-8", "smartbands", "HONOR"),
    ("Samsung Fit3", "samsung-fit3", "smartbands", "Samsung"),
    ("Fitbit Flex 2", "fitbit-flex-2", "smartbands", "Fitbit"),
    ("Jawbone Up24", "jawbone-up24", "smartbands", "Jawbone"),
    ("Misfit Flash", "misfit-flash", "smartbands", "Misfit"),
    ("Withings Pulse O2", "withings-pulse-o2", "smartbands", "Withings"),
    ("Apple Watch Ultra", "apple-watch-ultra", "smartbands", "Apple"),
    ("Garmin epix Gen 2", "garmin-epix-gen-2", "smartbands", "Garmin"),
    ("Polar Vantage M2", "polar-vantage-m2", "smartbands", "Polar"),
    ("Coros Pace 3", "coros-pace-3", "smartbands", "Coros"),
    ("Suunto 9 Baro", "suunto-9-baro", "smartbands", "Suunto"),
    ("Epson Prosense", "epson-prosense", "smartbands", "Epson"),
    ("Timex Ironman", "timex-ironman", "smartbands", "Timex"),
    ("Casio G-Shock", "casio-g-shock", "smartbands", "Casio"),
    ("Seiko 5 Sports", "seiko-5-sports", "smartbands", "Seiko"),
    ("Citizen Promaster", "citizen-promaster", "smartbands", "Citizen"),
    ("Orient Automata", "orient-automata", "smartbands", "Orient"),
    ("Invicta Pro Diver", "invicta-pro-diver", "smartbands", "Invicta"),
    ("Hamilton Khaki", "hamilton-khaki", "smartbands", "Hamilton"),
    ("Omega Seamaster", "omega-seamaster", "smartbands", "Omega"),
    ("Rolex Submariner", "rolex-submariner", "smartbands", "Rolex"),
    ("TAG Heuer Aquaracer", "tag-heuer-aquaracer", "smartbands", "TAG Heuer"),
]


async def seed_database():
    """Insert 450+ products with ultra-diverse brands."""
    engine = create_async_engine(settings.database_url, echo=False)

    # Create tables first
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with async_session() as session:
        created = 0
        for product_name, slug, category, brand in SEED_PRODUCTS_ULTRA:
            try:
                product = await repos.products.create(
                    session,
                    name=product_name,
                    slug=slug,
                    category=category,
                    brand=brand,
                    locale="in",
                )
                created += 1
            except Exception as e:
                print(f"✗ {product_name}: {str(e)[:80]}")

        await session.commit()
        print(f"\n✅ Seeded {created}/{len(SEED_PRODUCTS_ULTRA)} products")

        # Show distribution
        from sqlalchemy import select, func, text
        result = await session.execute(text("""
            SELECT category, COUNT(*) as count
            FROM products
            GROUP BY category
            ORDER BY COUNT(*) DESC
        """))
        print("\n📊 Ultra-Diverse Brand Distribution:")
        for row in result:
            print(f"  {row[0]:25} {row[1]:3} products")


if __name__ == "__main__":
    asyncio.run(seed_database())
